# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from abc import abstractmethod
from typing import Protocol


class WitWorld(Protocol):
    @abstractmethod
    def activate(self) -> None:
        raise NotImplementedError

    @abstractmethod
    def invoke(self, request: str) -> str:
        raise NotImplementedError
